#!/usr/bin/env python3
"""Static site generator for the MIA Toolkit website (stdlib only).

Renders templates/*.html × i18n/*.json into _site/: English at the root
(x-default), every other language under /<code>/. Generates the language
selector, canonical + hreflang cluster, Open Graph block, JSON-LD, the
sitemap, and redirect stubs for the pre-2026 flat URLs — so adding a language
is exactly one JSON file in i18n/.

Usage:  python3 website/build.py        (from the repo root or website/)
Output: website/_site/  (deployed by .github/workflows/pages.yml)
"""

from __future__ import annotations

import datetime
import html
import json
import os
import re
import shutil
import sys

import markdown  # build-time only (see website/requirements.txt)

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = "https://miatools.tech"

# Language order = dropdown order. English lives at the site root (x-default).
LANG_ORDER = ["en", "es", "zh", "ms", "ta", "de", "fr"]
HREFLANG = {"en": "en", "es": "es", "zh": "zh-Hans", "ms": "ms-SG",
            "ta": "ta-SG", "de": "de", "fr": "fr"}

PAGES = ["index", "help", "support", "privacy", "stats"]
OG_PAGES = {"index", "help", "support"}  # privacy has no social card (as before)

# The 6 guided-setup screens the /help walkthrough documents, in order (the
# `home` screenshot lives in the Overview, not the HowTo). Slugs drive the
# anchor ids, the image filenames, and the i18n key suffixes (hyphen→underscore).
HELP_STEPS = ["welcome", "add-studies", "review", "documents",
              "build-deliver", "done"]
HELP_FAQ_N = 8                            # number of FAQ Q&A pairs (faq_q1…)

ASSETS = ["styles.css", "lang.js", "download.js", "support.js", "robots.txt",
          "CNAME", "img", "version.json", "favicon.ico"]

# GoatCounter site code (e.g. "miatoolkit"). Empty = no analytics script is
# emitted AND the privacy policy keeps its "no analytics" wording. Setting it
# emits the cookieless beacon on every page and swaps in the privacy text that
# names GoatCounter — the build keeps the policy honest automatically.
GOATCOUNTER = "fritanga-collective"

# Legacy flat URLs -> new locations (meta-refresh + canonical stubs).
LEGACY = {
    "es.html": "/es/", "soporte.html": "/es/support.html",
    "privacidad.html": "/es/privacy.html",
    "zh.html": "/zh/", "support-zh.html": "/zh/support.html",
    "privacy-zh.html": "/zh/privacy.html",
}


def page_url(lang: str, page: str) -> str:
    """Root-absolute URL of a page in a language."""
    prefix = "/" if lang == "en" else f"/{lang}/"
    return prefix if page == "index" else f"{prefix}{page}.html"


def load_langs() -> dict[str, dict]:
    langs = {}
    for code in LANG_ORDER:
        path = os.path.join(HERE, "i18n", f"{code}.json")
        if not os.path.exists(path):
            print(f"  ! i18n/{code}.json missing — skipping {code}")
            continue
        with open(path, encoding="utf-8") as f:
            langs[code] = json.load(f)
    return langs


def langsel(langs: dict, lang: str, page: str) -> str:
    label = langs[lang].get("_selector_label", "Language")
    opts = []
    for code in langs:
        sel = " selected" if code == lang else ""
        opts.append(f'          <option value="{page_url(code, page)}"{sel}>'
                    f'{langs[code]["_lang_name"]}</option>')
    return (f'        <select class="langsel" aria-label="{label}"\n'
            '                onchange="if(this.value)location.href=this.value">\n'
            + "\n".join(opts) + "\n        </select>")


def _favicon_lines() -> list[str]:
    # Favicons (generated by scripts/make_icons.py from the master logo).
    # Shared by head_seo (pages) and blog_head_seo (blog), so both stay in sync.
    return [
        '  <link rel="icon" href="/favicon.ico" sizes="48x48">',
        '  <link rel="icon" type="image/png" sizes="32x32" '
        'href="/img/favicon-32.png">',
        '  <link rel="icon" type="image/png" sizes="16x16" '
        'href="/img/favicon-16.png">',
        '  <link rel="icon" type="image/png" sizes="192x192" '
        'href="/img/icon-192.png">',
        '  <link rel="apple-touch-icon" sizes="180x180" '
        'href="/img/apple-touch-icon.png">',
    ]


def head_seo(langs: dict, lang: str, page: str, s: dict) -> str:
    url = BASE + page_url(lang, page)
    lines = [f'  <link rel="canonical" href="{url}">'] + _favicon_lines()
    for code in langs:
        lines.append(f'  <link rel="alternate" hreflang="{HREFLANG[code]}" '
                     f'href="{BASE}{page_url(code, page)}">')
    lines.append(f'  <link rel="alternate" hreflang="x-default" '
                 f'href="{BASE}{page_url("en", page)}">')
    if page in OG_PAGES:
        title = s.get(f"{page}.og_title", s.get(f"{page}.title", ""))
        desc = s.get(f"{page}.meta_desc", "")
        lines += [
            '  <meta property="og:type" content="website">',
            '  <meta property="og:site_name" content="MIA Toolkit">',
            f'  <meta property="og:title" content="{title}">',
            f'  <meta property="og:description" content="{desc}">',
            f'  <meta property="og:url" content="{url}">',
            f'  <meta property="og:locale" content="{s["_og_locale"]}">',
        ]
        for code in langs:
            if code != lang:
                lines.append(f'  <meta property="og:locale:alternate" '
                             f'content="{langs[code]["_og_locale"]}">')
        lines += [
            f'  <meta property="og:image" content="{BASE}/img/social.jpg">',
            '  <meta property="og:image:width" content="1200">',
            '  <meta property="og:image:height" content="633">',
            f'  <meta property="og:image:alt" content="{title}">',
            '  <meta name="twitter:card" content="summary_large_image">',
            f'  <meta name="twitter:title" content="{title}">',
            f'  <meta name="twitter:description" content="{desc}">',
            f'  <meta name="twitter:image" content="{BASE}/img/social.jpg">',
        ]
    return "\n".join(lines)


def _ld_script(data: dict) -> str:
    return ('  <script type="application/ld+json">\n'
            + json.dumps(data, ensure_ascii=False, indent=2)
            + "\n  </script>")


def json_ld(lang: str, s: dict, page: str) -> str:
    if page == "index":
        data = {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "MIA Toolkit",
            "operatingSystem": "macOS, Windows",
            "applicationCategory": "HealthApplication",
            "url": BASE + page_url(lang, "index"),
            "downloadUrl": "https://github.com/Fritanga-Collective/mia-toolkit/releases/latest",
            "description": s["index.meta_desc"],
            "image": f"{BASE}/img/social.jpg",
            "isAccessibleForFree": True,
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
            "publisher": {"@type": "Organization", "name": "Fritanga",
                          "url": "https://fritanga.co"},
        }
        return _ld_script(data)

    if page == "help":
        # Localized HowTo (the walkthrough) + FAQPage (the FAQ), both built from
        # the i18n strings so each locale gets its own structured data.
        url = BASE + page_url(lang, "help")
        steps = []
        for slug in HELP_STEPS:
            k = slug.replace("-", "_")
            steps.append({
                "@type": "HowToStep",
                "name": s[f"help.s_{k}_h3"],
                "text": s[f"help.s_{k}_p"],
                "url": f"{url}#step-{slug}",
                "image": f"{BASE}/img/help/{lang}/{slug}.png",
            })
        howto = {
            "@context": "https://schema.org",
            "@type": "HowTo",
            "name": s["help.howto_name"],
            "description": s["help.meta_desc"],
            "image": f"{BASE}/img/help/{lang}/home.png",
            "totalTime": "PT15M",
            "step": steps,
        }
        faqpage = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {"@type": "Question", "name": s[f"help.faq_q{i}"],
                 "acceptedAnswer": {"@type": "Answer", "text": s[f"help.faq_a{i}"]}}
                for i in range(1, HELP_FAQ_N + 1)
            ],
        }
        return _ld_script(howto) + "\n" + _ld_script(faqpage)

    return ""


# ───────────────────────── blog (/blog) ─────────────────────────
# A self-hosted, multilingual blog under /blog. Posts are one markdown file per
# (post, language) at content/blog/<lang>/<slug>.md, with a `---`-fenced
# front-matter block. The same slug across languages forms a translation
# "cluster" (drives hreflang + the post's language switcher). en lives at
# /blog/ and /blog/<slug>/; other langs under /<lang>/blog/…  — mirroring the
# rest of the site. Only `status: published` posts are emitted, and only for
# languages that also carry the blog.* i18n keys (see load_posts/main).

import datetime as _dt
import email.utils as _eut

# Every blog.* i18n key the blog templates/renderers consume. A locale must
# carry ALL of these to be eligible — render() raises KeyError on the first
# missing key, so a partial set (e.g. only blog.index_title) must still skip.
REQUIRED_BLOG_KEYS = frozenset({
    "blog.index_title", "blog.meta_desc", "blog.published",
    "blog.back", "blog.read_more",
})


def blog_index_url(lang: str) -> str:
    return "/blog/" if lang == "en" else f"/{lang}/blog/"


def blog_post_url(lang: str, slug: str) -> str:
    return blog_index_url(lang) + f"{slug}/"


def _parse_front_matter(text: str) -> tuple[dict, str]:
    """Split a `---`-fenced front-matter block from the markdown body.

    A tiny stdlib parser (no YAML dep). Handles `key: value` and list values
    written as `key: [a, b]` or `key: ["a", "b"]`. Returns (meta, body).
    """
    if not text.startswith("---"):
        return {}, text
    # Front-matter is everything between the first two `---` lines.
    parts = text.split("\n", 1)[1].split("\n---", 1)
    if len(parts) != 2:
        return {}, text
    block, body = parts[0], parts[1]
    meta: dict = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":" not in line:
            continue
        key, _, raw = line.partition(":")
        key, raw = key.strip(), raw.strip()
        if raw.startswith("[") and raw.endswith("]"):
            items = [x.strip().strip('"').strip("'")
                     for x in raw[1:-1].split(",")]
            meta[key] = [x for x in items if x]
        else:
            meta[key] = raw.strip('"').strip("'")
    return meta, body.lstrip("\n")


# Scheduling: a post goes live only when its `date` (ISO YYYY-MM-DD) has
# arrived. A `status: published` post with a FUTURE date is "scheduled" and
# held until then — combined with the daily Pages rebuild (pages.yml cron), it
# publishes itself on its date with no manual push. Set BLOG_PREVIEW=1 to
# include future-dated posts (local preview / staging the upcoming week).
# Parse explicitly so "0"/"false"/"" do NOT enable preview (a bare bool() on the
# env value would treat any non-empty string, incl. "0", as on).
BLOG_PREVIEW = os.environ.get("BLOG_PREVIEW", "").strip().lower() in {
    "1", "true", "yes", "on"}


def _blog_today() -> datetime.date:
    return datetime.datetime.now(datetime.timezone.utc).date()


def _is_live(meta: dict, today: datetime.date) -> bool:
    """A published post is live once its date is today or earlier (UTC).

    Future-dated → held unless BLOG_PREVIEW. A missing/malformed date is treated
    as live now (back-compatible) — main() warns so it doesn't go unnoticed."""
    if BLOG_PREVIEW:
        return True
    raw = (meta.get("date") or "").strip()
    try:
        return datetime.date.fromisoformat(raw) <= today
    except ValueError:
        return True  # no/!ISO date → publish now (warned in main)


def load_posts() -> tuple[list[dict], dict[str, list[dict]]]:
    """Walk content/blog/<lang>/*.md → live post dicts + slug clusters.

    Each post dict carries: lang, slug, title, date, summary, languages, tags,
    status, image, translation, body (raw markdown). Keeps only
    status == "published" posts whose date has arrived (see _is_live;
    BLOG_PREVIEW=1 includes scheduled ones). Returns (posts, clusters) where
    clusters maps slug → [post, …] (every live language for that slug), used for
    hreflang + the language switcher.
    """
    root = os.path.join(HERE, "content", "blog")
    posts: list[dict] = []
    if not os.path.isdir(root):
        return posts, {}
    today = _blog_today()
    for lang in sorted(os.listdir(root)):
        ldir = os.path.join(root, lang)
        if not os.path.isdir(ldir):
            continue
        for name in sorted(os.listdir(ldir)):
            if not name.endswith(".md"):
                continue
            with open(os.path.join(ldir, name), encoding="utf-8") as f:
                meta, body = _parse_front_matter(f.read())
            if meta.get("status") != "published":
                continue
            if not _is_live(meta, today):
                continue  # scheduled for a future date — hold it
            try:
                datetime.date.fromisoformat((meta.get("date") or "").strip())
            except ValueError:
                print(f"  ! blog: {lang}/{name} has no/invalid ISO date "
                      f"({meta.get('date')!r}) — publishing now; set "
                      f"date: YYYY-MM-DD to schedule it")
            posts.append({
                "lang": lang,
                "slug": meta.get("slug") or name[:-3],
                "title": meta.get("title", ""),
                "date": meta.get("date", ""),
                "summary": meta.get("summary", ""),
                "languages": meta.get("languages", [lang]),
                "tags": meta.get("tags", []),
                "status": meta.get("status", ""),
                "image": meta.get("image", ""),
                "translation": meta.get("translation", ""),
                "body": body,
            })
    clusters: dict[str, list[dict]] = {}
    for p in posts:
        clusters.setdefault(p["slug"], []).append(p)
    return posts, clusters


def _post_image_url(post: dict) -> str:
    """Absolute social-card image for a post: its own `image` front-matter
    (http→as-is, root-relative→prefixed with BASE) or "" when it has none."""
    img = post.get("image", "")
    if not img:
        return ""
    return img if img.startswith("http") else BASE + img


def blog_head_seo(post: dict, cluster: list[dict]) -> str:
    """Canonical + hreflang (scoped to the cluster's langs) + OG article."""
    lang, slug = post["lang"], post["slug"]
    url = BASE + blog_post_url(lang, slug)
    cluster_langs = [p["lang"] for p in cluster]
    lines = [f'  <link rel="canonical" href="{url}">'] + _favicon_lines()
    for code in cluster_langs:
        lines.append(f'  <link rel="alternate" hreflang="{HREFLANG[code]}" '
                     f'href="{BASE}{blog_post_url(code, slug)}">')
    if "en" in cluster_langs:  # x-default → English when a translation exists
        lines.append(f'  <link rel="alternate" hreflang="x-default" '
                     f'href="{BASE}{blog_post_url("en", slug)}">')
    title = html.escape(post["title"], quote=True)
    desc = html.escape(post["summary"], quote=True)
    custom = _post_image_url(post)
    image = custom or f"{BASE}/img/social.jpg"
    lines += [
        '  <meta property="og:type" content="article">',
        '  <meta property="og:site_name" content="MIA Toolkit">',
        f'  <meta property="og:title" content="{title}">',
        f'  <meta property="og:description" content="{desc}">',
        f'  <meta property="og:url" content="{url}">',
        f'  <meta property="article:published_time" content="{post["date"]}">',
        f'  <meta property="og:image" content="{image}">',
    ]
    if not custom:  # 1200x633 describes social.jpg only
        lines += [
            '  <meta property="og:image:width" content="1200">',
            '  <meta property="og:image:height" content="633">',
        ]
    lines += [
        '  <meta name="twitter:card" content="summary_large_image">',
        f'  <meta name="twitter:title" content="{title}">',
        f'  <meta name="twitter:description" content="{desc}">',
        f'  <meta name="twitter:image" content="{image}">',
    ]
    return "\n".join(lines)


def blog_json_ld(post: dict, cluster: list[dict]) -> str:
    url = BASE + blog_post_url(post["lang"], post["slug"])
    data = {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        "headline": post["title"],
        "datePublished": post["date"],
        "inLanguage": HREFLANG.get(post["lang"], post["lang"]),
        "description": post["summary"],
        "image": _post_image_url(post) or f"{BASE}/img/social.jpg",
        "author": {"@type": "Organization", "name": "Fritanga",
                   "url": "https://fritanga.co"},
        "publisher": {"@type": "Organization", "name": "Fritanga",
                      "url": "https://fritanga.co"},
        "mainEntityOfPage": {"@type": "WebPage", "@id": url},
    }
    return _ld_script(data)


def _blog_langsel(langs: dict, current_lang: str, target: dict) -> str:
    """Render a language dropdown over ONLY the languages in `target` (the
    Wikipedia model: offer just the languages this content actually exists in,
    so switching always lands on a real translation). `target` maps lang code →
    URL. Omitted entirely when there's nothing to switch to (≤1 language)."""
    codes = [c for c in LANG_ORDER if c in target]
    if len(codes) <= 1:
        return ""
    label = langs[current_lang].get("_selector_label", "Language")
    opts = []
    for code in codes:
        sel = " selected" if code == current_lang else ""
        opts.append(f'          <option value="{target[code]}"{sel}>'
                    f'{langs[code]["_lang_name"]}</option>')
    return (f'        <select class="langsel" aria-label="{label}"\n'
            '                onchange="if(this.value)location.href=this.value">\n'
            + "\n".join(opts) + "\n        </select>")


def blog_langsel(cluster: list[dict], langs: dict, current_lang: str) -> str:
    """Post selector: only the languages this post is actually translated into,
    each pointing at the real translation (never the homepage, never a 404)."""
    slug = cluster[0]["slug"]
    target = {p["lang"]: blog_post_url(p["lang"], slug) for p in cluster}
    return _blog_langsel(langs, current_lang, target)


def _blog_chrome(lang: str, prefix: str) -> dict:
    """Root-relative nav/footer links + asset prefix shared by both templates."""
    return {
        "P": prefix,
        "HOME": page_url(lang, "index"),
        "HELP": page_url(lang, "help"),
        "SUPPORT": page_url(lang, "support"),
        "PRIVACY": page_url(lang, "privacy"),
        "STATS": page_url(lang, "stats"),
        "BLOG_INDEX": blog_index_url(lang),
    }


def render_post(post: dict, cluster: list[dict], langs: dict,
                template: str) -> str:
    s = langs[post["lang"]]
    body = markdown.markdown(post["body"],
                             extensions=["extra", "toc", "sane_lists"])
    # Honesty flag for machine-assisted translations (health-adjacent topic):
    # a subtle footer note inviting corrections. Localized via blog.mt_note when
    # present (added to the MT target locales), with an English fallback.
    if post.get("translation") == "machine":
        note = s.get("blog.mt_note", "Translated with machine assistance — "
                     "corrections welcome at "
                     "<a href=\"mailto:support@miatools.tech\">"
                     "support@miatools.tech</a>.")
        body += f'\n<p class="mt-note">{note}</p>'
    prefix = "../../" if post["lang"] == "en" else "../../../"
    computed = _blog_chrome(post["lang"], prefix)
    hero = ""
    if post.get("image"):
        alt = html.escape(post["title"], quote=True)
        hero = (f'      <figure class="blog-hero"><img src="{post["image"]}" '
                f'alt="{alt}" loading="lazy"></figure>')
    computed.update({
        "HEAD_SEO": blog_head_seo(post, cluster),
        "JSON_LD": blog_json_ld(post, cluster),
        "LANGSEL": blog_langsel(cluster, langs, post["lang"]),
        "BLOG_TITLE": html.escape(post["title"]),
        "BLOG_SUMMARY": html.escape(post["summary"], quote=True),
        "BLOG_DATE": post["date"],
        "BLOG_IMAGE": hero,
        "BLOG_BODY": body,
    })
    return render(template, s, computed)


def render_blog_index(lang: str, posts: list[dict], langs: dict,
                      template: str) -> str:
    s = langs[lang]
    mine = sorted((p for p in posts if p["lang"] == lang),
                  key=lambda p: p["date"], reverse=True)  # newest first
    items = []
    for p in mine:
        url = blog_post_url(lang, p["slug"])
        # Decorative thumbnail: a bare <img alt=""> (not a link) — the title link
        # is the single click/tab target, and a non-interactive image needs no
        # aria-hidden/tabindex, so there's no double-target or a11y conflict.
        thumb = (f'          <img class="blog-thumb" src="{p["image"]}" alt="" '
                 f'loading="lazy">\n') if p.get("image") else ""
        items.append(
            '        <li class="blog-item">\n'
            + thumb +
            '          <div class="blog-item-body">\n'
            f'            <h2><a href="{url}">{html.escape(p["title"])}</a></h2>\n'
            f'            <p class="post-meta">{s["blog.published"]} '
            f'<time datetime="{p["date"]}">{p["date"]}</time></p>\n'
            f'            <p>{html.escape(p["summary"])}</p>\n'
            f'            <p><a href="{url}">{s["blog.read_more"]}</a></p>\n'
            '          </div>\n'
            '        </li>')
    prefix = "../" if lang == "en" else "../../"
    computed = _blog_chrome(lang, prefix)
    computed.update({
        "HEAD_SEO": blog_index_head_seo(lang, langs, posts),
        "JSON_LD": "",
        "LANGSEL": blog_index_langsel(lang, langs, posts),
        "BLOG_INDEX_TITLE": s["blog.index_title"],
        "BLOG_LIST": "\n".join(items),
    })
    return render(template, s, computed)


def _blog_langs(posts: list[dict]) -> list[str]:
    """Languages (in LANG_ORDER) that have ≥1 published post."""
    have = {p["lang"] for p in posts}
    return [c for c in LANG_ORDER if c in have]


def blog_index_head_seo(lang: str, langs: dict, posts: list[dict]) -> str:
    """Canonical + hreflang for a blog index, scoped to langs that have posts."""
    url = BASE + blog_index_url(lang)
    codes = _blog_langs(posts)
    lines = [f'  <link rel="canonical" href="{url}">'] + _favicon_lines()
    for code in codes:
        lines.append(f'  <link rel="alternate" hreflang="{HREFLANG[code]}" '
                     f'href="{BASE}{blog_index_url(code)}">')
    if "en" in codes:
        lines.append(f'  <link rel="alternate" hreflang="x-default" '
                     f'href="{BASE}{blog_index_url("en")}">')
    title = html.escape(langs[lang]["blog.index_title"], quote=True)
    desc = html.escape(langs[lang]["blog.meta_desc"], quote=True)
    lines += [
        '  <meta property="og:type" content="website">',
        '  <meta property="og:site_name" content="MIA Toolkit">',
        f'  <meta property="og:title" content="{title}">',
        f'  <meta property="og:description" content="{desc}">',
        f'  <meta property="og:url" content="{url}">',
        f'  <meta property="og:image" content="{BASE}/img/social.jpg">',
        '  <meta property="og:image:width" content="1200">',
        '  <meta property="og:image:height" content="633">',
        '  <meta name="twitter:card" content="summary_large_image">',
        f'  <meta name="twitter:title" content="{title}">',
        f'  <meta name="twitter:description" content="{desc}">',
        f'  <meta name="twitter:image" content="{BASE}/img/social.jpg">',
    ]
    return "\n".join(lines)


def blog_index_langsel(lang: str, langs: dict, posts: list[dict]) -> str:
    """Index selector: only the languages that actually have a blog index
    (≥1 published post), each pointing at that language's index."""
    target = {c: blog_index_url(c) for c in _blog_langs(posts)}
    return _blog_langsel(langs, lang, target)


def rss_feed(en_posts: list[dict]) -> str:
    """Valid RSS 2.0 for the English blog (newest first). En only for now."""
    items = []
    for p in sorted(en_posts, key=lambda p: p["date"], reverse=True):
        link = BASE + blog_post_url("en", p["slug"])
        try:  # date is YYYY-MM-DD → RFC-822 pubDate
            d = _dt.datetime.strptime(p["date"], "%Y-%m-%d")
            pub = _eut.format_datetime(d.replace(tzinfo=_dt.timezone.utc))
        except ValueError:
            pub = ""
        items.append(
            "    <item>\n"
            f"      <title>{html.escape(p['title'])}</title>\n"
            f"      <link>{link}</link>\n"
            f"      <guid>{link}</guid>\n"
            + (f"      <pubDate>{pub}</pubDate>\n" if pub else "")
            + f"      <description>{html.escape(p['summary'])}</description>\n"
            "    </item>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<rss version="2.0">\n'
            '  <channel>\n'
            '    <title>The MIA Toolkit Blog</title>\n'
            f'    <link>{BASE}/blog/</link>\n'
            '    <description>Plain-language guides on organizing your medical '
            'imaging.</description>\n'
            '    <language>en</language>\n'
            f'    <atom:link xmlns:atom="http://www.w3.org/2005/Atom" '
            f'href="{BASE}/blog/feed.xml" rel="self" type="application/rss+xml"/>\n'
            + "\n".join(items)
            + "\n  </channel>\n</rss>\n")


def render(template: str, s: dict, computed: dict) -> str:
    out = template
    for key, value in computed.items():
        out = out.replace("{{" + key + "}}", value)

    def sub(m: re.Match) -> str:
        key = m.group(1)
        if key not in s:
            raise KeyError(f"missing i18n key: {key}")
        return s[key]

    out = re.sub(r"\{\{([\w.]+)\}\}", sub, out)
    return out


def redirect_stub(target: str) -> str:
    url = BASE + target
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url={target}">
  <link rel="canonical" href="{url}">
  <title>Redirecting…</title>
</head>
<body>
  <p>This page has moved: <a href="{target}">{url}</a></p>
</body>
</html>
"""


def _sitemap_url(loc: str, alt_pairs: list[tuple[str, str]]) -> str:
    """One <url> entry with xhtml:link hreflang alternates (code, href)."""
    alts = [f'    <xhtml:link rel="alternate" hreflang="{hl}" href="{href}"/>'
            for hl, href in alt_pairs]
    return "  <url>\n    <loc>" + loc + "</loc>\n" + "\n".join(alts) + "\n  </url>"


def sitemap(langs: dict, posts: list[dict] | None = None,
            clusters: dict | None = None) -> str:
    entries = []
    for page in PAGES:
        for lang in langs:
            loc = BASE + page_url(lang, page)
            pairs = [(HREFLANG[c], f"{BASE}{page_url(c, page)}") for c in langs]
            pairs.append(("x-default", f'{BASE}{page_url("en", page)}'))
            entries.append(_sitemap_url(loc, pairs))

    # Blog: one entry per index (langs with posts) + one per published post,
    # each with hreflang alternates scoped to its cluster / available langs.
    if posts:
        blog_langs = _blog_langs(posts)
        for lang in blog_langs:
            loc = BASE + blog_index_url(lang)
            pairs = [(HREFLANG[c], f"{BASE}{blog_index_url(c)}")
                     for c in blog_langs]
            if "en" in blog_langs:
                pairs.append(("x-default", f'{BASE}{blog_index_url("en")}'))
            entries.append(_sitemap_url(loc, pairs))
        # Only reference languages whose blog pages were actually emitted
        # (posts is already filtered to the guard-passing `ready` langs) — else
        # a post that exists for a skipped language would emit an hreflang
        # alternate pointing at a page that was never built.
        emitted_langs = {p["lang"] for p in posts}
        for p in posts:
            loc = BASE + blog_post_url(p["lang"], p["slug"])
            cl = (clusters or {}).get(p["slug"], [p])
            cl_langs = [c for c in LANG_ORDER
                        if c in {q["lang"] for q in cl} and c in emitted_langs]
            pairs = [(HREFLANG[c], f"{BASE}{blog_post_url(c, p['slug'])}")
                     for c in cl_langs]
            if "en" in cl_langs:
                pairs.append(("x-default",
                              f'{BASE}{blog_post_url("en", p["slug"])}'))
            entries.append(_sitemap_url(loc, pairs))

    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
            '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + "\n".join(entries) + "\n</urlset>\n")


def load_metrics():
    path = os.path.join(HERE, "data", "metrics.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def stats_chart_svg(snapshots, pending_text: str) -> str:
    """Build-time SVG bar chart of downloads/day — zero client JS."""
    if len(snapshots) < 2:
        return f'        <p class="note">{pending_text}</p>'
    days = []
    for prev, cur in zip(snapshots, snapshots[1:]):
        days.append((cur["date"], max(0, cur["total"] - prev["total"])))
    days = days[-60:]
    peak = max((n for _d, n in days), default=1) or 1
    w, h, pad = 640, 140, 4
    bw = max(2, (w - 2 * pad) // max(len(days), 1) - 2)
    bars = []
    for i, (d, n) in enumerate(days):
        bh = int((h - 30) * n / peak)
        x = pad + i * (bw + 2)
        bars.append(f'<rect x="{x}" y="{h - 20 - bh}" width="{bw}" '
                    f'height="{bh}" fill="#2c5282"><title>{d}: {n}</title></rect>')
    first, last = days[0][0], days[-1][0]
    return (f'        <svg viewBox="0 0 {w} {h}" role="img" class="stats-chart" '
            f'preserveAspectRatio="xMidYMid meet">'
            + "".join(bars)
            + f'<text x="{pad}" y="{h - 4}" font-size="11" fill="#4a5568">{first}</text>'
            + f'<text x="{w - pad}" y="{h - 4}" font-size="11" fill="#4a5568" '
              f'text-anchor="end">{last}</text></svg>')


def stats_blocks(metrics, s: dict) -> dict:
    empty4 = '            <tr><td colspan="4">—</td></tr>'
    empty2 = '            <tr><td colspan="2">—</td></tr>'
    if not metrics:
        return {"STATS_UPDATED": "—", "STATS_TOTAL": "—", "STATS_CHART": "",
                "STATS_TABLE": empty4, "STATS_VIEWS": "—", "STATS_UNIQUES": "—",
                "STATS_REFERRERS": empty2}
    snaps = metrics.get("snapshots", [])
    latest = snaps[-1] if snaps else {}
    rows = []
    for r in metrics.get("releases", []):
        mac = sum(a["count"] for a in r["assets"] if a["name"].endswith(".dmg"))
        win = sum(a["count"] for a in r["assets"] if a["name"].endswith(".exe"))
        rows.append(f'            <tr><td>{html.escape(r["tag"])}</td>'
                    f'<td>{mac:,}</td>'
                    f'<td>{win:,}</td><td>{mac + win:,}</td></tr>')
    rows = rows or [empty4]
    refs = [f'            <tr><td>{html.escape(r["referrer"])}</td>'
            f'<td>{r["count"]:,}</td></tr>'
            for r in metrics.get("referrers", [])] or [empty2]
    return {
        "STATS_UPDATED": metrics.get("updated", "—"),
        "STATS_TOTAL": f'{latest.get("total", 0):,}',
        "STATS_CHART": stats_chart_svg(snaps, s.get("stats.chart_pending", "")),
        "STATS_TABLE": "\n".join(rows),
        "STATS_VIEWS": f'{latest.get("views14", 0):,}',
        "STATS_UNIQUES": f'{latest.get("uniques14", 0):,}',
        "STATS_REFERRERS": "\n".join(refs),
    }


GC_SNIPPET = ('  <script data-goatcounter="https://{code}.goatcounter.com/count"\n'
              '          async src="https://gc.zgo.at/count.js"></script>\n')


def _inject_gc(html_str: str) -> str:
    """Inject the cookieless GoatCounter beacon before the LAST </body> (if
    enabled). Using the last close tag is robust to a stray '</body>' appearing
    inside blog Markdown (raw HTML), which would otherwise misplace the beacon."""
    if not GOATCOUNTER:
        return html_str
    snippet = GC_SNIPPET.format(code=GOATCOUNTER)
    i = html_str.rfind("</body>")
    if i == -1:
        return html_str + snippet
    return html_str[:i] + snippet + html_str[i:]


def main() -> int:
    langs = load_langs()
    if "en" not in langs:
        print("FATAL: i18n/en.json is required")
        return 1
    site = os.path.join(HERE, "_site")
    shutil.rmtree(site, ignore_errors=True)
    os.makedirs(site)

    templates = {p: open(os.path.join(HERE, "templates", f"{p}.html"),
                         encoding="utf-8").read() for p in PAGES}
    metrics = load_metrics()

    pages = 0
    for lang, s in langs.items():
        if GOATCOUNTER and "privacy.site_li1_gc" in s:
            s = dict(s)
            s["privacy.site_li1"] = s["privacy.site_li1_gc"]
        outdir = site if lang == "en" else os.path.join(site, lang)
        os.makedirs(outdir, exist_ok=True)
        prefix = "" if lang == "en" else "../"
        for page in PAGES:
            computed = {
                "P": prefix,
                "LANG": lang,   # directory code (en/es/zh/…), not the _lang
                                # locale (es-MX); used for per-language asset paths
                "HEAD_SEO": head_seo(langs, lang, page, s),
                "JSON_LD": json_ld(lang, s, page),
                "LANGSEL": langsel(langs, lang, page),
            }
            if page == "stats":
                computed.update(stats_blocks(metrics, s))
            html = _inject_gc(render(templates[page], s, computed))
            with open(os.path.join(outdir, f"{page}.html"), "w",
                      encoding="utf-8") as f:
                f.write(html)
            pages += 1

    # ── Blog (/blog) ──────────────────────────────────────────────
    # Only emit blog pages for languages that (a) have ≥1 published post AND
    # (b) carry the blog.* i18n keys — render() raises KeyError on a missing
    # key, so a future es post without es blog.* keys must NOT crash the build.
    all_posts, clusters = load_posts()
    blog_tmpl = {
        "index": open(os.path.join(HERE, "templates", "blog_index.html"),
                      encoding="utf-8").read(),
        "post": open(os.path.join(HERE, "templates", "blog_post.html"),
                     encoding="utf-8").read(),
    }
    ready = {c for c in _blog_langs(all_posts)
             if c in langs and REQUIRED_BLOG_KEYS <= langs[c].keys()}
    skipped = sorted({p["lang"] for p in all_posts} - ready)
    for c in skipped:
        if c not in langs:
            print(f"  ! blog: skipping {c} — i18n/{c}.json not loaded "
                  f"(not in LANG_ORDER or file missing)")
        else:
            missing = ", ".join(sorted(REQUIRED_BLOG_KEYS - langs[c].keys()))
            print(f"  ! blog: skipping {c} — missing blog.* i18n keys "
                  f"({missing}) in i18n/{c}.json")
    posts = [p for p in all_posts if p["lang"] in ready]
    blog_pages = 0
    if posts:
        for lang in _blog_langs(posts):
            outdir = (os.path.join(site, "blog") if lang == "en"
                      else os.path.join(site, lang, "blog"))
            os.makedirs(outdir, exist_ok=True)
            idx = _inject_gc(render_blog_index(lang, posts, langs,
                                               blog_tmpl["index"]))
            with open(os.path.join(outdir, "index.html"), "w",
                      encoding="utf-8") as f:
                f.write(idx)
            blog_pages += 1
        for p in posts:
            cluster = [q for q in clusters[p["slug"]] if q["lang"] in ready]
            postdir = os.path.join(site, "" if p["lang"] == "en" else p["lang"],
                                   "blog", p["slug"])
            os.makedirs(postdir, exist_ok=True)
            out = _inject_gc(render_post(p, cluster, langs, blog_tmpl["post"]))
            with open(os.path.join(postdir, "index.html"), "w",
                      encoding="utf-8") as f:
                f.write(out)
            blog_pages += 1
        # RSS for the English blog only (for now).
        en_posts = [p for p in posts if p["lang"] == "en"]
        if en_posts:
            os.makedirs(os.path.join(site, "blog"), exist_ok=True)
            with open(os.path.join(site, "blog", "feed.xml"), "w",
                      encoding="utf-8") as f:
                f.write(rss_feed(en_posts))

    for legacy, target in LEGACY.items():
        with open(os.path.join(site, legacy), "w", encoding="utf-8") as f:
            f.write(redirect_stub(target))

    with open(os.path.join(site, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(sitemap(langs, posts, clusters))

    for asset in ASSETS:
        src = os.path.join(HERE, asset)
        if not os.path.exists(src):
            print(f"  ! asset missing: {asset}")
            continue
        dst = os.path.join(site, asset)
        if os.path.isdir(src):
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

    print(f"✓ built {pages} pages × {len(langs)} languages "
          f"({', '.join(langs)}), {blog_pages} blog pages "
          f"({len(posts)} posts), {len(LEGACY)} redirects, sitemap, assets "
          f"→ {os.path.relpath(site)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
