#!/usr/bin/env python3
"""Static site generator for the MIA Toolkit website (stdlib only).

Renders templates/*.html × i18n/*.json into _site/: English at the root
(x-default), every other language under /<code>/. Generates the language
selector, canonical + hreflang cluster, Open Graph block, JSON-LD, the
sitemap, and redirect stubs for the pre-2026 flat URLs — so adding a language
is exactly one JSON file in i18n/.

Usage:  python3 website/build.py        (from the repo root or website/)
Output: website/_site/  (deployed by .github/workflows/pages.yml)
"""

from __future__ import annotations

import html
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = "https://miatools.tech"

# Language order = dropdown order. English lives at the site root (x-default).
LANG_ORDER = ["en", "es", "zh", "ms", "ta", "de"]
HREFLANG = {"en": "en", "es": "es", "zh": "zh-Hans", "ms": "ms-SG",
            "ta": "ta-SG", "de": "de"}

PAGES = ["index", "help", "support", "privacy", "stats"]
OG_PAGES = {"index", "help", "support"}  # privacy has no social card (as before)

# The 6 guided-setup screens the /help walkthrough documents, in order (the
# `home` screenshot lives in the Overview, not the HowTo). Slugs drive the
# anchor ids, the image filenames, and the i18n key suffixes (hyphen→underscore).
HELP_STEPS = ["welcome", "add-studies", "review", "documents",
              "build-deliver", "done"]
HELP_FAQ_N = 8                            # number of FAQ Q&A pairs (faq_q1…)

ASSETS = ["styles.css", "lang.js", "download.js", "support.js", "robots.txt",
          "CNAME", "img", "version.json", "favicon.ico"]

# GoatCounter site code (e.g. "miatoolkit"). Empty = no analytics script is
# emitted AND the privacy policy keeps its "no analytics" wording. Setting it
# emits the cookieless beacon on every page and swaps in the privacy text that
# names GoatCounter — the build keeps the policy honest automatically.
GOATCOUNTER = "fritanga-collective"

# Legacy flat URLs -> new locations (meta-refresh + canonical stubs).
LEGACY = {
    "es.html": "/es/", "soporte.html": "/es/support.html",
    "privacidad.html": "/es/privacy.html",
    "zh.html": "/zh/", "support-zh.html": "/zh/support.html",
    "privacy-zh.html": "/zh/privacy.html",
}


def page_url(lang: str, page: str) -> str:
    """Root-absolute URL of a page in a language."""
    prefix = "/" if lang == "en" else f"/{lang}/"
    return prefix if page == "index" else f"{prefix}{page}.html"


def load_langs() -> dict[str, dict]:
    langs = {}
    for code in LANG_ORDER:
        path = os.path.join(HERE, "i18n", f"{code}.json")
        if not os.path.exists(path):
            print(f"  ! i18n/{code}.json missing — skipping {code}")
            continue
        with open(path, encoding="utf-8") as f:
            langs[code] = json.load(f)
    return langs


def langsel(langs: dict, lang: str, page: str) -> str:
    label = langs[lang].get("_selector_label", "Language")
    opts = []
    for code in langs:
        sel = " selected" if code == lang else ""
        opts.append(f'          <option value="{page_url(code, page)}"{sel}>'
                    f'{langs[code]["_lang_name"]}</option>')
    return (f'        <select class="langsel" aria-label="{label}"\n'
            '                onchange="if(this.value)location.href=this.value">\n'
            + "\n".join(opts) + "\n        </select>")


def head_seo(langs: dict, lang: str, page: str, s: dict) -> str:
    url = BASE + page_url(lang, page)
    lines = [
        f'  <link rel="canonical" href="{url}">',
        # Favicons (generated by scripts/make_icons.py from the master logo).
        '  <link rel="icon" href="/favicon.ico" sizes="48x48">',
        '  <link rel="icon" type="image/png" sizes="32x32" '
        'href="/img/favicon-32.png">',
        '  <link rel="icon" type="image/png" sizes="16x16" '
        'href="/img/favicon-16.png">',
        '  <link rel="icon" type="image/png" sizes="192x192" '
        'href="/img/icon-192.png">',
        '  <link rel="apple-touch-icon" sizes="180x180" '
        'href="/img/apple-touch-icon.png">',
    ]
    for code in langs:
        lines.append(f'  <link rel="alternate" hreflang="{HREFLANG[code]}" '
                     f'href="{BASE}{page_url(code, page)}">')
    lines.append(f'  <link rel="alternate" hreflang="x-default" '
                 f'href="{BASE}{page_url("en", page)}">')
    if page in OG_PAGES:
        title = s.get(f"{page}.og_title", s.get(f"{page}.title", ""))
        desc = s.get(f"{page}.meta_desc", "")
        lines += [
            '  <meta property="og:type" content="website">',
            '  <meta property="og:site_name" content="MIA Toolkit">',
            f'  <meta property="og:title" content="{title}">',
            f'  <meta property="og:description" content="{desc}">',
            f'  <meta property="og:url" content="{url}">',
            f'  <meta property="og:locale" content="{s["_og_locale"]}">',
        ]
        for code in langs:
            if code != lang:
                lines.append(f'  <meta property="og:locale:alternate" '
                             f'content="{langs[code]["_og_locale"]}">')
        lines += [
            f'  <meta property="og:image" content="{BASE}/img/social.jpg">',
            '  <meta property="og:image:width" content="1200">',
            '  <meta property="og:image:height" content="633">',
            f'  <meta property="og:image:alt" content="{title}">',
            '  <meta name="twitter:card" content="summary_large_image">',
            f'  <meta name="twitter:title" content="{title}">',
            f'  <meta name="twitter:description" content="{desc}">',
            f'  <meta name="twitter:image" content="{BASE}/img/social.jpg">',
        ]
    return "\n".join(lines)


def _ld_script(data: dict) -> str:
    return ('  <script type="application/ld+json">\n'
            + json.dumps(data, ensure_ascii=False, indent=2)
            + "\n  </script>")


def json_ld(lang: str, s: dict, page: str) -> str:
    if page == "index":
        data = {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "MIA Toolkit",
            "operatingSystem": "macOS, Windows",
            "applicationCategory": "HealthApplication",
            "url": BASE + page_url(lang, "index"),
            "downloadUrl": "https://github.com/Fritanga-Collective/mia-toolkit/releases/latest",
            "description": s["index.meta_desc"],
            "image": f"{BASE}/img/social.jpg",
            "isAccessibleForFree": True,
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
            "publisher": {"@type": "Organization", "name": "Fritanga",
                          "url": "https://fritanga.co"},
        }
        return _ld_script(data)

    if page == "help":
        # Localized HowTo (the walkthrough) + FAQPage (the FAQ), both built from
        # the i18n strings so each locale gets its own structured data.
        url = BASE + page_url(lang, "help")
        steps = []
        for slug in HELP_STEPS:
            k = slug.replace("-", "_")
            steps.append({
                "@type": "HowToStep",
                "name": s[f"help.s_{k}_h3"],
                "text": s[f"help.s_{k}_p"],
                "url": f"{url}#step-{slug}",
                "image": f"{BASE}/img/help/{lang}/{slug}.png",
            })
        howto = {
            "@context": "https://schema.org",
            "@type": "HowTo",
            "name": s["help.howto_name"],
            "description": s["help.meta_desc"],
            "image": f"{BASE}/img/help/{lang}/home.png",
            "totalTime": "PT15M",
            "step": steps,
        }
        faqpage = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [
                {"@type": "Question", "name": s[f"help.faq_q{i}"],
                 "acceptedAnswer": {"@type": "Answer", "text": s[f"help.faq_a{i}"]}}
                for i in range(1, HELP_FAQ_N + 1)
            ],
        }
        return _ld_script(howto) + "\n" + _ld_script(faqpage)

    return ""


def render(template: str, s: dict, computed: dict) -> str:
    out = template
    for key, value in computed.items():
        out = out.replace("{{" + key + "}}", value)

    def sub(m: re.Match) -> str:
        key = m.group(1)
        if key not in s:
            raise KeyError(f"missing i18n key: {key}")
        return s[key]

    out = re.sub(r"\{\{([\w.]+)\}\}", sub, out)
    return out


def redirect_stub(target: str) -> str:
    url = BASE + target
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url={target}">
  <link rel="canonical" href="{url}">
  <title>Redirecting…</title>
</head>
<body>
  <p>This page has moved: <a href="{target}">{url}</a></p>
</body>
</html>
"""


def sitemap(langs: dict) -> str:
    entries = []
    for page in PAGES:
        for lang in langs:
            loc = BASE + page_url(lang, page)
            alts = [f'    <xhtml:link rel="alternate" hreflang="{HREFLANG[c]}"'
                    f' href="{BASE}{page_url(c, page)}"/>' for c in langs]
            alts.append(f'    <xhtml:link rel="alternate" hreflang="x-default"'
                        f' href="{BASE}{page_url("en", page)}"/>')
            entries.append("  <url>\n    <loc>" + loc + "</loc>\n"
                           + "\n".join(alts) + "\n  </url>")
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n'
            '        xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
            + "\n".join(entries) + "\n</urlset>\n")


def load_metrics():
    path = os.path.join(HERE, "data", "metrics.json")
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def stats_chart_svg(snapshots, pending_text: str) -> str:
    """Build-time SVG bar chart of downloads/day — zero client JS."""
    if len(snapshots) < 2:
        return f'        <p class="note">{pending_text}</p>'
    days = []
    for prev, cur in zip(snapshots, snapshots[1:]):
        days.append((cur["date"], max(0, cur["total"] - prev["total"])))
    days = days[-60:]
    peak = max((n for _d, n in days), default=1) or 1
    w, h, pad = 640, 140, 4
    bw = max(2, (w - 2 * pad) // max(len(days), 1) - 2)
    bars = []
    for i, (d, n) in enumerate(days):
        bh = int((h - 30) * n / peak)
        x = pad + i * (bw + 2)
        bars.append(f'<rect x="{x}" y="{h - 20 - bh}" width="{bw}" '
                    f'height="{bh}" fill="#2c5282"><title>{d}: {n}</title></rect>')
    first, last = days[0][0], days[-1][0]
    return (f'        <svg viewBox="0 0 {w} {h}" role="img" class="stats-chart" '
            f'preserveAspectRatio="xMidYMid meet">'
            + "".join(bars)
            + f'<text x="{pad}" y="{h - 4}" font-size="11" fill="#4a5568">{first}</text>'
            + f'<text x="{w - pad}" y="{h - 4}" font-size="11" fill="#4a5568" '
              f'text-anchor="end">{last}</text></svg>')


def stats_blocks(metrics, s: dict) -> dict:
    empty4 = '            <tr><td colspan="4">—</td></tr>'
    empty2 = '            <tr><td colspan="2">—</td></tr>'
    if not metrics:
        return {"STATS_UPDATED": "—", "STATS_TOTAL": "—", "STATS_CHART": "",
                "STATS_TABLE": empty4, "STATS_VIEWS": "—", "STATS_UNIQUES": "—",
                "STATS_REFERRERS": empty2}
    snaps = metrics.get("snapshots", [])
    latest = snaps[-1] if snaps else {}
    rows = []
    for r in metrics.get("releases", []):
        mac = sum(a["count"] for a in r["assets"] if a["name"].endswith(".dmg"))
        win = sum(a["count"] for a in r["assets"] if a["name"].endswith(".exe"))
        rows.append(f'            <tr><td>{html.escape(r["tag"])}</td>'
                    f'<td>{mac:,}</td>'
                    f'<td>{win:,}</td><td>{mac + win:,}</td></tr>')
    rows = rows or [empty4]
    refs = [f'            <tr><td>{html.escape(r["referrer"])}</td>'
            f'<td>{r["count"]:,}</td></tr>'
            for r in metrics.get("referrers", [])] or [empty2]
    return {
        "STATS_UPDATED": metrics.get("updated", "—"),
        "STATS_TOTAL": f'{latest.get("total", 0):,}',
        "STATS_CHART": stats_chart_svg(snaps, s.get("stats.chart_pending", "")),
        "STATS_TABLE": "\n".join(rows),
        "STATS_VIEWS": f'{latest.get("views14", 0):,}',
        "STATS_UNIQUES": f'{latest.get("uniques14", 0):,}',
        "STATS_REFERRERS": "\n".join(refs),
    }


GC_SNIPPET = ('  <script data-goatcounter="https://{code}.goatcounter.com/count"\n'
              '          async src="https://gc.zgo.at/count.js"></script>\n')


def main() -> int:
    langs = load_langs()
    if "en" not in langs:
        print("FATAL: i18n/en.json is required")
        return 1
    site = os.path.join(HERE, "_site")
    shutil.rmtree(site, ignore_errors=True)
    os.makedirs(site)

    templates = {p: open(os.path.join(HERE, "templates", f"{p}.html"),
                         encoding="utf-8").read() for p in PAGES}
    metrics = load_metrics()

    pages = 0
    for lang, s in langs.items():
        if GOATCOUNTER and "privacy.site_li1_gc" in s:
            s = dict(s)
            s["privacy.site_li1"] = s["privacy.site_li1_gc"]
        outdir = site if lang == "en" else os.path.join(site, lang)
        os.makedirs(outdir, exist_ok=True)
        prefix = "" if lang == "en" else "../"
        for page in PAGES:
            computed = {
                "P": prefix,
                "LANG": lang,   # directory code (en/es/zh/…), not the _lang
                                # locale (es-MX); used for per-language asset paths
                "HEAD_SEO": head_seo(langs, lang, page, s),
                "JSON_LD": json_ld(lang, s, page),
                "LANGSEL": langsel(langs, lang, page),
            }
            if page == "stats":
                computed.update(stats_blocks(metrics, s))
            html = render(templates[page], s, computed)
            if GOATCOUNTER:
                html = html.replace("</body>",
                                    GC_SNIPPET.format(code=GOATCOUNTER)
                                    + "</body>")
            with open(os.path.join(outdir, f"{page}.html"), "w",
                      encoding="utf-8") as f:
                f.write(html)
            pages += 1

    for legacy, target in LEGACY.items():
        with open(os.path.join(site, legacy), "w", encoding="utf-8") as f:
            f.write(redirect_stub(target))

    with open(os.path.join(site, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(sitemap(langs))

    for asset in ASSETS:
        src = os.path.join(HERE, asset)
        if not os.path.exists(src):
            print(f"  ! asset missing: {asset}")
            continue
        dst = os.path.join(site, asset)
        if os.path.isdir(src):
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)

    print(f"✓ built {pages} pages × {len(langs)} languages "
          f"({', '.join(langs)}), {len(LEGACY)} redirects, sitemap, assets "
          f"→ {os.path.relpath(site)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
